version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-docker
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password